-- =============================================================================
-- Migration: Add ideal_state_prompts table
-- Purpose: Store AI-generated prompts for fine-tuning and quality analysis
-- Date: 2025-11-11
-- =============================================================================

-- =============================================================================
-- 1. Create ideal_state_prompts table
-- =============================================================================

CREATE TABLE IF NOT EXISTS ideal_state_prompts (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  category TEXT NOT NULL,
  
  -- The generated prompts array
  prompts JSONB NOT NULL,
  -- Structure: [
  --   {"title": "string", "prompt": "string", "focus": "string"},
  --   ...
  -- ]
  
  -- Encouragement message
  encouragement TEXT,
  
  -- AI metadata for fine-tuning
  model_used TEXT,
  tokens_used INTEGER,
  response_time_ms INTEGER,
  
  -- Timestamps
  created_at TIMESTAMPTZ DEFAULT NOW(),
  
  -- Constraints
  CONSTRAINT valid_category CHECK (category IN (
    'fun', 'health', 'travel', 'love', 'family', 'social',
    'home', 'work', 'money', 'stuff', 'giving', 'spirituality'
  ))
);

COMMENT ON TABLE ideal_state_prompts IS 'Stores AI-generated prompts for Step 2 (Unleash Imagination) for fine-tuning analysis';
COMMENT ON COLUMN ideal_state_prompts.prompts IS 'JSONB array of {title, prompt, focus} objects generated by VIVA';
COMMENT ON COLUMN ideal_state_prompts.encouragement IS 'VIVA''s encouragement message for this category';
COMMENT ON COLUMN ideal_state_prompts.model_used IS 'AI model used for generation (e.g., gpt-4o-mini)';
COMMENT ON COLUMN ideal_state_prompts.tokens_used IS 'Total tokens consumed for generation';

-- =============================================================================
-- 2. Create indexes for performance
-- =============================================================================

-- Index for user + category lookups (most common query)
CREATE INDEX IF NOT EXISTS idx_ideal_state_prompts_user_category 
  ON ideal_state_prompts(user_id, category);

-- Index for recent prompts
CREATE INDEX IF NOT EXISTS idx_ideal_state_prompts_created_at 
  ON ideal_state_prompts(created_at DESC);

-- GIN index on prompts JSONB for advanced queries
CREATE INDEX IF NOT EXISTS idx_ideal_state_prompts_jsonb 
  ON ideal_state_prompts USING GIN (prompts);

-- =============================================================================
-- 3. Add Row Level Security (RLS)
-- =============================================================================

ALTER TABLE ideal_state_prompts ENABLE ROW LEVEL SECURITY;

-- Users can only see their own prompts
CREATE POLICY "Users can view their own ideal state prompts"
  ON ideal_state_prompts
  FOR SELECT
  USING (auth.uid() = user_id);

-- Users can insert their own prompts
CREATE POLICY "Users can insert their own ideal state prompts"
  ON ideal_state_prompts
  FOR INSERT
  WITH CHECK (auth.uid() = user_id);

-- Users can update their own prompts (rare, but allowed)
CREATE POLICY "Users can update their own ideal state prompts"
  ON ideal_state_prompts
  FOR UPDATE
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- Users can delete their own prompts
CREATE POLICY "Users can delete their own ideal state prompts"
  ON ideal_state_prompts
  FOR DELETE
  USING (auth.uid() = user_id);

-- =============================================================================
-- 4. Create helper function for getting latest prompts
-- =============================================================================

CREATE OR REPLACE FUNCTION get_latest_ideal_state_prompts(
  p_user_id UUID,
  p_category TEXT
)
RETURNS TABLE (
  id UUID,
  prompts JSONB,
  encouragement TEXT,
  created_at TIMESTAMPTZ
) AS $$
BEGIN
  RETURN QUERY
  SELECT 
    isp.id,
    isp.prompts,
    isp.encouragement,
    isp.created_at
  FROM ideal_state_prompts isp
  WHERE isp.user_id = p_user_id
    AND isp.category = p_category
  ORDER BY isp.created_at DESC
  LIMIT 1;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

COMMENT ON FUNCTION get_latest_ideal_state_prompts IS 'Helper function to get the most recent prompts for a user/category';

-- =============================================================================
-- ROLLBACK INSTRUCTIONS (if needed)
-- =============================================================================

-- To rollback these changes, run:
--
-- DROP FUNCTION IF EXISTS get_latest_ideal_state_prompts(UUID, TEXT);
-- DROP POLICY IF EXISTS "Users can delete their own ideal state prompts" ON ideal_state_prompts;
-- DROP POLICY IF EXISTS "Users can update their own ideal state prompts" ON ideal_state_prompts;
-- DROP POLICY IF EXISTS "Users can insert their own ideal state prompts" ON ideal_state_prompts;
-- DROP POLICY IF EXISTS "Users can view their own ideal state prompts" ON ideal_state_prompts;
-- DROP INDEX IF EXISTS idx_ideal_state_prompts_jsonb;
-- DROP INDEX IF EXISTS idx_ideal_state_prompts_created_at;
-- DROP INDEX IF EXISTS idx_ideal_state_prompts_user_category;
-- DROP TABLE IF EXISTS ideal_state_prompts;

