-- Seed music_catalog with VibrationFit's 34 published songs
-- Run after uploading assets to S3: site-assets/music/{slug}/audio.wav + artwork.jpg
-- CDN: https://media.vibrationfit.com/site-assets/music/{slug}/...

-- Christmas songs (sort_order 500+ so year-round singles appear first on Listen > Music)
INSERT INTO music_catalog (title, artist, album, track_number, genre, tags, artwork_url, preview_url, sort_order) VALUES
('A Childlike Christmas', 'Vibration Fit', 'High Vibe Christmas', 1, 'Holiday', '{}', 'https://media.vibrationfit.com/site-assets/music/a-childlike-christmas/artwork.jpg', 'https://media.vibrationfit.com/site-assets/music/a-childlike-christmas/audio.wav', 501),
('Believe In The Magic of Christmas', 'Vibration Fit', 'High Vibe Christmas', 2, 'Holiday', '{}', 'https://media.vibrationfit.com/site-assets/music/believe-in-the-magic-of-christmas/artwork.jpg', 'https://media.vibrationfit.com/site-assets/music/believe-in-the-magic-of-christmas/audio.wav', 502),
('Feel Good This Christmas', 'Vibration Fit', 'High Vibe Christmas', 3, 'Holiday', '{}', 'https://media.vibrationfit.com/site-assets/music/feel-good-this-christmas/artwork.jpg', 'https://media.vibrationfit.com/site-assets/music/feel-good-this-christmas/audio.wav', 503),
('High Vibe Christmas', 'Vibration Fit', 'High Vibe Christmas', 4, 'Holiday', '{}', 'https://media.vibrationfit.com/site-assets/music/high-vibe-christmas/artwork.jpg', 'https://media.vibrationfit.com/site-assets/music/high-vibe-christmas/audio.wav', 504),
('This Christmas Dance', 'Vibration Fit', 'High Vibe Christmas', 5, 'Holiday', '{}', 'https://media.vibrationfit.com/site-assets/music/this-christmas-dance/artwork.jpg', 'https://media.vibrationfit.com/site-assets/music/this-christmas-dance/audio.wav', 505),
('Turn It Up This Christmas', 'Vibration Fit', 'High Vibe Christmas', 6, 'Holiday', '{}', 'https://media.vibrationfit.com/site-assets/music/turn-it-up-this-christmas/artwork.jpg', 'https://media.vibrationfit.com/site-assets/music/turn-it-up-this-christmas/audio.wav', 506);

-- Originals (non-Christmas) - sorted alphabetically, you can reorder / assign albums later
INSERT INTO music_catalog (title, artist, genre, tags, artwork_url, preview_url, sort_order) VALUES
('Allow It In', 'Vibration Fit', 'Inspirational', '{}', 'https://media.vibrationfit.com/site-assets/music/allow-it-in/artwork.jpg', 'https://media.vibrationfit.com/site-assets/music/allow-it-in/audio.wav', 10),
('Avalanches of Abundance', 'Vibration Fit', 'Inspirational', '{}', 'https://media.vibrationfit.com/site-assets/music/avalanches-of-abundance/artwork.jpg', 'https://media.vibrationfit.com/site-assets/music/avalanches-of-abundance/audio.wav', 11),
('Best Day Ever', 'Vibration Fit', 'Inspirational', '{}', 'https://media.vibrationfit.com/site-assets/music/best-day-ever/artwork.jpg', 'https://media.vibrationfit.com/site-assets/music/best-day-ever/audio.wav', 12),
('BIG Feelings', 'Vibration Fit', 'Inspirational', '{}', 'https://media.vibrationfit.com/site-assets/music/big-feelings/artwork.jpg', 'https://media.vibrationfit.com/site-assets/music/big-feelings/audio.wav', 13),
('Breath Like Water', 'Vibration Fit', 'Wellness', '{}', 'https://media.vibrationfit.com/site-assets/music/breath-like-water/artwork.jpg', 'https://media.vibrationfit.com/site-assets/music/breath-like-water/audio.wav', 14),
('Every Cell', 'Vibration Fit', 'Wellness', '{}', 'https://media.vibrationfit.com/site-assets/music/every-cell/artwork.jpg', 'https://media.vibrationfit.com/site-assets/music/every-cell/audio.wav', 15),
('Every Piece of Me', 'Vibration Fit', 'Inspirational', '{}', 'https://media.vibrationfit.com/site-assets/music/every-piece-of-me/artwork.jpg', 'https://media.vibrationfit.com/site-assets/music/every-piece-of-me/audio.wav', 16),
('Everything Always Works Out For Me', 'Vibration Fit', 'Inspirational', '{}', 'https://media.vibrationfit.com/site-assets/music/everything-always-works-out-for-me/artwork.jpg', 'https://media.vibrationfit.com/site-assets/music/everything-always-works-out-for-me/audio.wav', 17),
('Home In Me', 'Vibration Fit', 'Inspirational', '{}', 'https://media.vibrationfit.com/site-assets/music/home-in-me/artwork.jpg', 'https://media.vibrationfit.com/site-assets/music/home-in-me/audio.wav', 18),
('I''ll Wait for Magic', 'Vibration Fit', 'Inspirational', '{}', 'https://media.vibrationfit.com/site-assets/music/ill-wait-for-magic/artwork.jpg', 'https://media.vibrationfit.com/site-assets/music/ill-wait-for-magic/audio.wav', 19),
('Mirror Maze', 'Vibration Fit', 'Inspirational', '{}', 'https://media.vibrationfit.com/site-assets/music/mirror-maze/artwork.jpg', 'https://media.vibrationfit.com/site-assets/music/mirror-maze/audio.wav', 20),
('Model of the World', 'Vibration Fit', 'Inspirational', '{}', 'https://media.vibrationfit.com/site-assets/music/model-of-the-world/artwork.jpg', 'https://media.vibrationfit.com/site-assets/music/model-of-the-world/audio.wav', 21),
('Moments Make the Miles', 'Vibration Fit', 'Inspirational', '{}', 'https://media.vibrationfit.com/site-assets/music/moments-make-the-miles/artwork.jpg', 'https://media.vibrationfit.com/site-assets/music/moments-make-the-miles/audio.wav', 22),
('Music the Powerful Soul-ution', 'Vibration Fit', 'Inspirational', '{}', 'https://media.vibrationfit.com/site-assets/music/music-the-powerful-soul-ution/artwork.jpg', 'https://media.vibrationfit.com/site-assets/music/music-the-powerful-soul-ution/audio.wav', 23),
('My Shelter', 'Vibration Fit', 'Inspirational', '{}', 'https://media.vibrationfit.com/site-assets/music/my-shelter/artwork.jpg', 'https://media.vibrationfit.com/site-assets/music/my-shelter/audio.wav', 24),
('Power in Now', 'Vibration Fit', 'Wellness', '{}', 'https://media.vibrationfit.com/site-assets/music/power-in-now/artwork.jpg', 'https://media.vibrationfit.com/site-assets/music/power-in-now/audio.wav', 25),
('Right On Time', 'Vibration Fit', 'Inspirational', '{}', 'https://media.vibrationfit.com/site-assets/music/right-on-time/artwork.jpg', 'https://media.vibrationfit.com/site-assets/music/right-on-time/audio.wav', 26),
('Rise to Well-Being', 'Vibration Fit', 'Wellness', '{}', 'https://media.vibrationfit.com/site-assets/music/rise-to-well-being/artwork.jpg', 'https://media.vibrationfit.com/site-assets/music/rise-to-well-being/audio.wav', 27),
('Speak It Into Being', 'Vibration Fit', 'Inspirational', '{}', 'https://media.vibrationfit.com/site-assets/music/speak-it-into-being/artwork.jpg', 'https://media.vibrationfit.com/site-assets/music/speak-it-into-being/audio.wav', 28),
('The Guidance Within', 'Vibration Fit', 'Inspirational', '{}', 'https://media.vibrationfit.com/site-assets/music/the-guidance-within/artwork.jpg', 'https://media.vibrationfit.com/site-assets/music/the-guidance-within/audio.wav', 29),
('The Life I Choose', 'Vibration Fit', 'Inspirational', '{spirituality}', 'https://media.vibrationfit.com/site-assets/music/the-life-i-choose/artwork.jpg', 'https://media.vibrationfit.com/site-assets/music/the-life-i-choose/audio.wav', 30),
('The Next Right Thing', 'Vibration Fit', 'Inspirational', '{}', 'https://media.vibrationfit.com/site-assets/music/the-next-right-thing/artwork.jpg', 'https://media.vibrationfit.com/site-assets/music/the-next-right-thing/audio.wav', 31),
('They Chose Me', 'Vibration Fit', 'Inspirational', '{}', 'https://media.vibrationfit.com/site-assets/music/they-chose-me/artwork.jpg', 'https://media.vibrationfit.com/site-assets/music/they-chose-me/audio.wav', 32),
('To Know Me Through Me', 'Vibration Fit', 'Inspirational', '{}', 'https://media.vibrationfit.com/site-assets/music/to-know-me-through-me/artwork.jpg', 'https://media.vibrationfit.com/site-assets/music/to-know-me-through-me/audio.wav', 33),
('Vibrational Fitness', 'Vibration Fit', 'Inspirational', '{}', 'https://media.vibrationfit.com/site-assets/music/vibrational-fitness/artwork.jpg', 'https://media.vibrationfit.com/site-assets/music/vibrational-fitness/audio.wav', 34),
('Vibrational Universe', 'Vibration Fit', 'Inspirational', '{}', 'https://media.vibrationfit.com/site-assets/music/vibrational-universe/artwork.jpg', 'https://media.vibrationfit.com/site-assets/music/vibrational-universe/audio.wav', 35),
('Wake Up Creator', 'Vibration Fit', 'Inspirational', '{}', 'https://media.vibrationfit.com/site-assets/music/wake-up-creator/artwork.jpg', 'https://media.vibrationfit.com/site-assets/music/wake-up-creator/audio.wav', 36),
('Wildflower Wishes', 'Vibration Fit', 'Inspirational', '{}', 'https://media.vibrationfit.com/site-assets/music/wildflower-wishes/artwork.jpg', 'https://media.vibrationfit.com/site-assets/music/wildflower-wishes/audio.wav', 37);
