// ISO 3166-1 countries: alpha-2 code, English name, numeric code.
// numeric matches the feature ids in world-atlas TopoJSON (public/data/world-110m.json).

export interface Country {
  code: string
  name: string
  numeric: string
}

export const COUNTRIES: Country[] = [
  { code: "AF", name: "Afghanistan", numeric: "004" },
  { code: "AX", name: "Åland Islands", numeric: "248" },
  { code: "AL", name: "Albania", numeric: "008" },
  { code: "DZ", name: "Algeria", numeric: "012" },
  { code: "AS", name: "American Samoa", numeric: "016" },
  { code: "AD", name: "Andorra", numeric: "020" },
  { code: "AO", name: "Angola", numeric: "024" },
  { code: "AI", name: "Anguilla", numeric: "660" },
  { code: "AQ", name: "Antarctica", numeric: "010" },
  { code: "AG", name: "Antigua and Barbuda", numeric: "028" },
  { code: "AR", name: "Argentina", numeric: "032" },
  { code: "AM", name: "Armenia", numeric: "051" },
  { code: "AW", name: "Aruba", numeric: "533" },
  { code: "AU", name: "Australia", numeric: "036" },
  { code: "AT", name: "Austria", numeric: "040" },
  { code: "AZ", name: "Azerbaijan", numeric: "031" },
  { code: "BS", name: "Bahamas", numeric: "044" },
  { code: "BH", name: "Bahrain", numeric: "048" },
  { code: "BD", name: "Bangladesh", numeric: "050" },
  { code: "BB", name: "Barbados", numeric: "052" },
  { code: "BY", name: "Belarus", numeric: "112" },
  { code: "BE", name: "Belgium", numeric: "056" },
  { code: "BZ", name: "Belize", numeric: "084" },
  { code: "BJ", name: "Benin", numeric: "204" },
  { code: "BM", name: "Bermuda", numeric: "060" },
  { code: "BT", name: "Bhutan", numeric: "064" },
  { code: "BO", name: "Bolivia, Plurinational State of", numeric: "068" },
  { code: "BQ", name: "Bonaire, Sint Eustatius and Saba", numeric: "535" },
  { code: "BA", name: "Bosnia and Herzegovina", numeric: "070" },
  { code: "BW", name: "Botswana", numeric: "072" },
  { code: "BV", name: "Bouvet Island", numeric: "074" },
  { code: "BR", name: "Brazil", numeric: "076" },
  { code: "IO", name: "British Indian Ocean Territory", numeric: "086" },
  { code: "BN", name: "Brunei Darussalam", numeric: "096" },
  { code: "BG", name: "Bulgaria", numeric: "100" },
  { code: "BF", name: "Burkina Faso", numeric: "854" },
  { code: "BI", name: "Burundi", numeric: "108" },
  { code: "CV", name: "Cabo Verde", numeric: "132" },
  { code: "KH", name: "Cambodia", numeric: "116" },
  { code: "CM", name: "Cameroon", numeric: "120" },
  { code: "CA", name: "Canada", numeric: "124" },
  { code: "KY", name: "Cayman Islands", numeric: "136" },
  { code: "CF", name: "Central African Republic", numeric: "140" },
  { code: "TD", name: "Chad", numeric: "148" },
  { code: "CL", name: "Chile", numeric: "152" },
  { code: "CN", name: "China", numeric: "156" },
  { code: "CX", name: "Christmas Island", numeric: "162" },
  { code: "CC", name: "Cocos (Keeling) Islands", numeric: "166" },
  { code: "CO", name: "Colombia", numeric: "170" },
  { code: "KM", name: "Comoros", numeric: "174" },
  { code: "CG", name: "Congo", numeric: "178" },
  { code: "CD", name: "Congo, Democratic Republic of the", numeric: "180" },
  { code: "CK", name: "Cook Islands", numeric: "184" },
  { code: "CR", name: "Costa Rica", numeric: "188" },
  { code: "CI", name: "Côte d'Ivoire", numeric: "384" },
  { code: "HR", name: "Croatia", numeric: "191" },
  { code: "CU", name: "Cuba", numeric: "192" },
  { code: "CW", name: "Curaçao", numeric: "531" },
  { code: "CY", name: "Cyprus", numeric: "196" },
  { code: "CZ", name: "Czechia", numeric: "203" },
  { code: "DK", name: "Denmark", numeric: "208" },
  { code: "DJ", name: "Djibouti", numeric: "262" },
  { code: "DM", name: "Dominica", numeric: "212" },
  { code: "DO", name: "Dominican Republic", numeric: "214" },
  { code: "EC", name: "Ecuador", numeric: "218" },
  { code: "EG", name: "Egypt", numeric: "818" },
  { code: "SV", name: "El Salvador", numeric: "222" },
  { code: "GQ", name: "Equatorial Guinea", numeric: "226" },
  { code: "ER", name: "Eritrea", numeric: "232" },
  { code: "EE", name: "Estonia", numeric: "233" },
  { code: "SZ", name: "Eswatini", numeric: "748" },
  { code: "ET", name: "Ethiopia", numeric: "231" },
  { code: "FK", name: "Falkland Islands (Malvinas)", numeric: "238" },
  { code: "FO", name: "Faroe Islands", numeric: "234" },
  { code: "FJ", name: "Fiji", numeric: "242" },
  { code: "FI", name: "Finland", numeric: "246" },
  { code: "FR", name: "France", numeric: "250" },
  { code: "GF", name: "French Guiana", numeric: "254" },
  { code: "PF", name: "French Polynesia", numeric: "258" },
  { code: "TF", name: "French Southern Territories", numeric: "260" },
  { code: "GA", name: "Gabon", numeric: "266" },
  { code: "GM", name: "Gambia", numeric: "270" },
  { code: "GE", name: "Georgia", numeric: "268" },
  { code: "DE", name: "Germany", numeric: "276" },
  { code: "GH", name: "Ghana", numeric: "288" },
  { code: "GI", name: "Gibraltar", numeric: "292" },
  { code: "GR", name: "Greece", numeric: "300" },
  { code: "GL", name: "Greenland", numeric: "304" },
  { code: "GD", name: "Grenada", numeric: "308" },
  { code: "GP", name: "Guadeloupe", numeric: "312" },
  { code: "GU", name: "Guam", numeric: "316" },
  { code: "GT", name: "Guatemala", numeric: "320" },
  { code: "GG", name: "Guernsey", numeric: "831" },
  { code: "GN", name: "Guinea", numeric: "324" },
  { code: "GW", name: "Guinea-Bissau", numeric: "624" },
  { code: "GY", name: "Guyana", numeric: "328" },
  { code: "HT", name: "Haiti", numeric: "332" },
  { code: "HM", name: "Heard Island and McDonald Islands", numeric: "334" },
  { code: "VA", name: "Holy See", numeric: "336" },
  { code: "HN", name: "Honduras", numeric: "340" },
  { code: "HK", name: "Hong Kong", numeric: "344" },
  { code: "HU", name: "Hungary", numeric: "348" },
  { code: "IS", name: "Iceland", numeric: "352" },
  { code: "IN", name: "India", numeric: "356" },
  { code: "ID", name: "Indonesia", numeric: "360" },
  { code: "IR", name: "Iran, Islamic Republic of", numeric: "364" },
  { code: "IQ", name: "Iraq", numeric: "368" },
  { code: "IE", name: "Ireland", numeric: "372" },
  { code: "IM", name: "Isle of Man", numeric: "833" },
  { code: "IL", name: "Israel", numeric: "376" },
  { code: "IT", name: "Italy", numeric: "380" },
  { code: "JM", name: "Jamaica", numeric: "388" },
  { code: "JP", name: "Japan", numeric: "392" },
  { code: "JE", name: "Jersey", numeric: "832" },
  { code: "JO", name: "Jordan", numeric: "400" },
  { code: "KZ", name: "Kazakhstan", numeric: "398" },
  { code: "KE", name: "Kenya", numeric: "404" },
  { code: "KI", name: "Kiribati", numeric: "296" },
  { code: "KP", name: "Korea, Democratic People's Republic of", numeric: "408" },
  { code: "KR", name: "Korea, Republic of", numeric: "410" },
  { code: "KW", name: "Kuwait", numeric: "414" },
  { code: "KG", name: "Kyrgyzstan", numeric: "417" },
  { code: "LA", name: "Lao People's Democratic Republic", numeric: "418" },
  { code: "LV", name: "Latvia", numeric: "428" },
  { code: "LB", name: "Lebanon", numeric: "422" },
  { code: "LS", name: "Lesotho", numeric: "426" },
  { code: "LR", name: "Liberia", numeric: "430" },
  { code: "LY", name: "Libya", numeric: "434" },
  { code: "LI", name: "Liechtenstein", numeric: "438" },
  { code: "LT", name: "Lithuania", numeric: "440" },
  { code: "LU", name: "Luxembourg", numeric: "442" },
  { code: "MO", name: "Macao", numeric: "446" },
  { code: "MG", name: "Madagascar", numeric: "450" },
  { code: "MW", name: "Malawi", numeric: "454" },
  { code: "MY", name: "Malaysia", numeric: "458" },
  { code: "MV", name: "Maldives", numeric: "462" },
  { code: "ML", name: "Mali", numeric: "466" },
  { code: "MT", name: "Malta", numeric: "470" },
  { code: "MH", name: "Marshall Islands", numeric: "584" },
  { code: "MQ", name: "Martinique", numeric: "474" },
  { code: "MR", name: "Mauritania", numeric: "478" },
  { code: "MU", name: "Mauritius", numeric: "480" },
  { code: "YT", name: "Mayotte", numeric: "175" },
  { code: "MX", name: "Mexico", numeric: "484" },
  { code: "FM", name: "Micronesia, Federated States of", numeric: "583" },
  { code: "MD", name: "Moldova, Republic of", numeric: "498" },
  { code: "MC", name: "Monaco", numeric: "492" },
  { code: "MN", name: "Mongolia", numeric: "496" },
  { code: "ME", name: "Montenegro", numeric: "499" },
  { code: "MS", name: "Montserrat", numeric: "500" },
  { code: "MA", name: "Morocco", numeric: "504" },
  { code: "MZ", name: "Mozambique", numeric: "508" },
  { code: "MM", name: "Myanmar", numeric: "104" },
  { code: "NA", name: "Namibia", numeric: "516" },
  { code: "NR", name: "Nauru", numeric: "520" },
  { code: "NP", name: "Nepal", numeric: "524" },
  { code: "NL", name: "Netherlands, Kingdom of the", numeric: "528" },
  { code: "NC", name: "New Caledonia", numeric: "540" },
  { code: "NZ", name: "New Zealand", numeric: "554" },
  { code: "NI", name: "Nicaragua", numeric: "558" },
  { code: "NE", name: "Niger", numeric: "562" },
  { code: "NG", name: "Nigeria", numeric: "566" },
  { code: "NU", name: "Niue", numeric: "570" },
  { code: "NF", name: "Norfolk Island", numeric: "574" },
  { code: "MK", name: "North Macedonia", numeric: "807" },
  { code: "MP", name: "Northern Mariana Islands", numeric: "580" },
  { code: "NO", name: "Norway", numeric: "578" },
  { code: "OM", name: "Oman", numeric: "512" },
  { code: "PK", name: "Pakistan", numeric: "586" },
  { code: "PW", name: "Palau", numeric: "585" },
  { code: "PS", name: "Palestine, State of", numeric: "275" },
  { code: "PA", name: "Panama", numeric: "591" },
  { code: "PG", name: "Papua New Guinea", numeric: "598" },
  { code: "PY", name: "Paraguay", numeric: "600" },
  { code: "PE", name: "Peru", numeric: "604" },
  { code: "PH", name: "Philippines", numeric: "608" },
  { code: "PN", name: "Pitcairn", numeric: "612" },
  { code: "PL", name: "Poland", numeric: "616" },
  { code: "PT", name: "Portugal", numeric: "620" },
  { code: "PR", name: "Puerto Rico", numeric: "630" },
  { code: "QA", name: "Qatar", numeric: "634" },
  { code: "RE", name: "Réunion", numeric: "638" },
  { code: "RO", name: "Romania", numeric: "642" },
  { code: "RU", name: "Russian Federation", numeric: "643" },
  { code: "RW", name: "Rwanda", numeric: "646" },
  { code: "BL", name: "Saint Barthélemy", numeric: "652" },
  { code: "SH", name: "Saint Helena, Ascension and Tristan da Cunha", numeric: "654" },
  { code: "KN", name: "Saint Kitts and Nevis", numeric: "659" },
  { code: "LC", name: "Saint Lucia", numeric: "662" },
  { code: "MF", name: "Saint Martin (French part)", numeric: "663" },
  { code: "PM", name: "Saint Pierre and Miquelon", numeric: "666" },
  { code: "VC", name: "Saint Vincent and the Grenadines", numeric: "670" },
  { code: "WS", name: "Samoa", numeric: "882" },
  { code: "SM", name: "San Marino", numeric: "674" },
  { code: "ST", name: "Sao Tome and Principe", numeric: "678" },
  { code: "SA", name: "Saudi Arabia", numeric: "682" },
  { code: "SN", name: "Senegal", numeric: "686" },
  { code: "RS", name: "Serbia", numeric: "688" },
  { code: "SC", name: "Seychelles", numeric: "690" },
  { code: "SL", name: "Sierra Leone", numeric: "694" },
  { code: "SG", name: "Singapore", numeric: "702" },
  { code: "SX", name: "Sint Maarten (Dutch part)", numeric: "534" },
  { code: "SK", name: "Slovakia", numeric: "703" },
  { code: "SI", name: "Slovenia", numeric: "705" },
  { code: "SB", name: "Solomon Islands", numeric: "090" },
  { code: "SO", name: "Somalia", numeric: "706" },
  { code: "ZA", name: "South Africa", numeric: "710" },
  { code: "GS", name: "South Georgia and the South Sandwich Islands", numeric: "239" },
  { code: "SS", name: "South Sudan", numeric: "728" },
  { code: "ES", name: "Spain", numeric: "724" },
  { code: "LK", name: "Sri Lanka", numeric: "144" },
  { code: "SD", name: "Sudan", numeric: "729" },
  { code: "SR", name: "Suriname", numeric: "740" },
  { code: "SJ", name: "Svalbard and Jan Mayen", numeric: "744" },
  { code: "SE", name: "Sweden", numeric: "752" },
  { code: "CH", name: "Switzerland", numeric: "756" },
  { code: "SY", name: "Syrian Arab Republic", numeric: "760" },
  { code: "TW", name: "Taiwan, Province of China", numeric: "158" },
  { code: "TJ", name: "Tajikistan", numeric: "762" },
  { code: "TZ", name: "Tanzania, United Republic of", numeric: "834" },
  { code: "TH", name: "Thailand", numeric: "764" },
  { code: "TL", name: "Timor-Leste", numeric: "626" },
  { code: "TG", name: "Togo", numeric: "768" },
  { code: "TK", name: "Tokelau", numeric: "772" },
  { code: "TO", name: "Tonga", numeric: "776" },
  { code: "TT", name: "Trinidad and Tobago", numeric: "780" },
  { code: "TN", name: "Tunisia", numeric: "788" },
  { code: "TR", name: "Türkiye", numeric: "792" },
  { code: "TM", name: "Turkmenistan", numeric: "795" },
  { code: "TC", name: "Turks and Caicos Islands", numeric: "796" },
  { code: "TV", name: "Tuvalu", numeric: "798" },
  { code: "UG", name: "Uganda", numeric: "800" },
  { code: "UA", name: "Ukraine", numeric: "804" },
  { code: "AE", name: "United Arab Emirates", numeric: "784" },
  { code: "GB", name: "United Kingdom of Great Britain and Northern Ireland", numeric: "826" },
  { code: "US", name: "United States of America", numeric: "840" },
  { code: "UM", name: "United States Minor Outlying Islands", numeric: "581" },
  { code: "UY", name: "Uruguay", numeric: "858" },
  { code: "UZ", name: "Uzbekistan", numeric: "860" },
  { code: "VU", name: "Vanuatu", numeric: "548" },
  { code: "VE", name: "Venezuela, Bolivarian Republic of", numeric: "862" },
  { code: "VN", name: "Viet Nam", numeric: "704" },
  { code: "VG", name: "Virgin Islands (British)", numeric: "092" },
  { code: "VI", name: "Virgin Islands (U.S.)", numeric: "850" },
  { code: "WF", name: "Wallis and Futuna", numeric: "876" },
  { code: "EH", name: "Western Sahara", numeric: "732" },
  { code: "YE", name: "Yemen", numeric: "887" },
  { code: "ZM", name: "Zambia", numeric: "894" },
  { code: "ZW", name: "Zimbabwe", numeric: "716" },
]

const BY_CODE = new Map(COUNTRIES.map((c) => [c.code, c]))
const BY_NUMERIC = new Map(COUNTRIES.map((c) => [c.numeric, c]))

export function countryName(code: string | null | undefined): string | null {
  if (!code) return null
  return BY_CODE.get(code.toUpperCase())?.name || null
}

export function countryNumeric(code: string | null | undefined): string | null {
  if (!code) return null
  return BY_CODE.get(code.toUpperCase())?.numeric || null
}

export function countryByNumeric(numeric: string | null | undefined): Country | null {
  if (!numeric) return null
  return BY_NUMERIC.get(numeric.padStart(3, '0')) || null
}
